window.BURR_PAW_LOCATIONS = {
  "locations": [
    {
      "id": "chandler-scheels-chandler-az",
      "name": "Chandler Scheels",
      "category": "retail",
      "address": "3199 W Chandler Blvd, Chandler, AZ 85226",
      "city": "Chandler",
      "state": "AZ",
      "zip": "85226",
      "lat": 33.3141,
      "lng": -111.8512,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Chandler Scheels."
    },
    {
      "id": "gila-valley-outdoor-llc-thatcher-az",
      "name": "Gila Valley Outdoor, LLC",
      "category": "retail",
      "address": "3660 W Main St, Thatcher, AZ 85552",
      "city": "Thatcher",
      "state": "AZ",
      "zip": "85552",
      "lat": 32.8512,
      "lng": -109.7506,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Gila Valley Outdoor, LLC."
    },
    {
      "id": "ross-outdoors-phoenix-az",
      "name": "Ross Outdoors",
      "category": "retail",
      "address": "407 S 17th Ave, Phoenix, AZ 85007",
      "city": "Phoenix",
      "state": "AZ",
      "zip": "85007",
      "lat": 33.4444,
      "lng": -112.0641,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Ross Outdoors."
    },
    {
      "id": "colorado-springs-scheels-colorado-springs-co",
      "name": "Colorado Springs Scheels",
      "category": "retail",
      "address": "1226 Interquest Parkway, Colorado Springs, CO 80921",
      "city": "Colorado Springs",
      "state": "CO",
      "zip": "80921",
      "lat": 38.8384,
      "lng": -104.816,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Colorado Springs Scheels."
    },
    {
      "id": "johnstown-scheels-johnstown-co",
      "name": "Johnstown Scheels",
      "category": "retail",
      "address": "4755 Ronald Reagan Blvd, Johnstown, CO 80534",
      "city": "Johnstown",
      "state": "CO",
      "zip": "80534",
      "lat": 40.3355,
      "lng": -104.9129,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Johnstown Scheels."
    },
    {
      "id": "adventures-archery-tampa-fl",
      "name": "Adventures Archery",
      "category": "retail",
      "address": "2210 S US Highway 301 Suite 200, Tampa, FL 33619",
      "city": "Tampa",
      "state": "FL",
      "zip": "33619",
      "lat": 27.9476,
      "lng": -82.457,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Adventures Archery."
    },
    {
      "id": "chicago-archery-wood-dale-il",
      "name": "Chicago Archery",
      "category": "retail",
      "address": "365 Georgetown Square, Wood Dale, IL 60191",
      "city": "Wood Dale",
      "state": "IL",
      "zip": "60191",
      "lat": 41.9685,
      "lng": -87.979,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Chicago Archery."
    },
    {
      "id": "dark-night-outdoors-milan-il",
      "name": "Dark Night Outdoors",
      "category": "retail",
      "address": "11618 6th Street, Milan, IL 61264",
      "city": "Milan",
      "state": "IL",
      "zip": "61264",
      "lat": 41.4334,
      "lng": -90.5718,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Dark Night Outdoors."
    },
    {
      "id": "game-masters-quincy-il",
      "name": "Game Masters",
      "category": "retail",
      "address": "5100 Broadway, Quincy, IL 62305",
      "city": "Quincy",
      "state": "IL",
      "zip": "62305",
      "lat": 39.9346,
      "lng": -91.4183,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Game Masters."
    },
    {
      "id": "hunters-haven-champaign-il",
      "name": "Hunters Haven",
      "category": "retail",
      "address": "1040 W Bloomington Road, Champaign, IL 61821",
      "city": "Champaign",
      "state": "IL",
      "zip": "61821",
      "lat": 40.1134,
      "lng": -88.2348,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Hunters Haven."
    },
    {
      "id": "morel-mania-magnolia-il",
      "name": "Morel Mania",
      "category": "retail",
      "address": "IL-18, Magnolia, IL 61336",
      "city": "Magnolia",
      "state": "IL",
      "zip": "61336",
      "lat": 41.1031,
      "lng": -89.2231,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Morel Mania."
    },
    {
      "id": "north-american-outfitters-highland-il",
      "name": "North American Outfitters",
      "category": "retail",
      "address": "13104 US-40, Highland, IL 62249",
      "city": "Highland",
      "state": "IL",
      "zip": "62249",
      "lat": 38.741,
      "lng": -89.6657,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at North American Outfitters."
    },
    {
      "id": "pike-county-archery-pittsfield-il",
      "name": "Pike County Archery",
      "category": "retail",
      "address": "7 E Industrial Dr, Pittsfield, IL 62363",
      "city": "Pittsfield",
      "state": "IL",
      "zip": "62363",
      "lat": 39.603,
      "lng": -90.8131,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Pike County Archery."
    },
    {
      "id": "pure-outdoor-alliance-havana-il",
      "name": "Pure Outdoor Alliance",
      "category": "retail",
      "address": "215 W Main St, Havana, IL 62644",
      "city": "Havana",
      "state": "IL",
      "zip": "62644",
      "lat": 40.3014,
      "lng": -90.0604,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Pure Outdoor Alliance."
    },
    {
      "id": "quincy-bow-pro-quincy-il",
      "name": "Quincy Bow Pro",
      "category": "retail",
      "address": "3112 Broadway St, Quincy, IL 62301",
      "city": "Quincy",
      "state": "IL",
      "zip": "62301",
      "lat": 39.9267,
      "lng": -91.4076,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Quincy Bow Pro."
    },
    {
      "id": "rummy-outdoors-morris-il",
      "name": "Rummy Outdoors",
      "category": "retail",
      "address": "927 N Gorham Rd, Morris, IL 60450",
      "city": "Morris",
      "state": "IL",
      "zip": "60450",
      "lat": 41.3535,
      "lng": -88.4261,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Rummy Outdoors."
    },
    {
      "id": "springfield-scheels-springfield-il",
      "name": "Springfield Scheels",
      "category": "retail",
      "address": "3801 S MacArthur Blvd, Springfield, IL 62711",
      "city": "Springfield",
      "state": "IL",
      "zip": "62711",
      "lat": 39.7895,
      "lng": -89.6414,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Springfield Scheels."
    },
    {
      "id": "grooming-n-style-bargersville-in",
      "name": "Grooming N Style",
      "category": "retail",
      "address": "504 E Old Plank Road, Bargersville, IN 46106",
      "city": "Bargersville",
      "state": "IN",
      "zip": "46106",
      "lat": 39.519,
      "lng": -86.163,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Grooming N Style."
    },
    {
      "id": "archery-field-sports-altoona-ia",
      "name": "Archery Field & Sports",
      "category": "retail",
      "address": "3725 NE 56th St, Altoona, IA 50009",
      "city": "Altoona",
      "state": "IA",
      "zip": "50009",
      "lat": 41.637,
      "lng": -93.4673,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Archery Field & Sports."
    },
    {
      "id": "cedar-falls-scheels-cedar-falls-ia",
      "name": "Cedar Falls Scheels",
      "category": "retail",
      "address": "402 Viking Plaza Dr, Cedar Falls, IA 50613",
      "city": "Cedar Falls",
      "state": "IA",
      "zip": "50613",
      "lat": 42.5445,
      "lng": -92.4364,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Cedar Falls Scheels."
    },
    {
      "id": "des-moines-scheels-west-des-moines-ia",
      "name": "Des Moines Scheels",
      "category": "retail",
      "address": "101 Jordan Creek Parkway Suite 4000, West Des Moines, IA 50266",
      "city": "West Des Moines",
      "state": "IA",
      "zip": "50266",
      "lat": 41.5733,
      "lng": -93.7072,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": true,
      "description": "Find Burr Paw at Des Moines Scheels."
    },
    {
      "id": "f6-outdoors-salem-ia",
      "name": "F6 Outdoors",
      "category": "retail",
      "address": "3027 Old Highway 218, Salem, IA 52649",
      "city": "Salem",
      "state": "IA",
      "zip": "52649",
      "lat": 40.8442,
      "lng": -91.6223,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at F6 Outdoors."
    },
    {
      "id": "fin-feather-iowa-city-ia",
      "name": "Fin & Feather",
      "category": "retail",
      "address": "125 Highway 1 W, Iowa City, IA 52246",
      "city": "Iowa City",
      "state": "IA",
      "zip": "52246",
      "lat": 41.6664,
      "lng": -91.5326,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Fin & Feather."
    },
    {
      "id": "fitzs-coon-shack-ames-ia",
      "name": "Fitzs Coon Shack",
      "category": "retail",
      "address": "616 Ridgewood, Ames, IA 50010",
      "city": "Ames",
      "state": "IA",
      "zip": "50010",
      "lat": 42.0281,
      "lng": -93.6361,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Fitzs Coon Shack."
    },
    {
      "id": "goliath-sporting-goods-spirit-lake-ia",
      "name": "Goliath Sporting Goods",
      "category": "retail",
      "address": "708 18th St, Spirit Lake, IA 51360",
      "city": "Spirit Lake",
      "state": "IA",
      "zip": "51360",
      "lat": 43.4227,
      "lng": -95.1003,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Goliath Sporting Goods."
    },
    {
      "id": "iowa-city-scheels-coralville-ia",
      "name": "Iowa City Scheels",
      "category": "retail",
      "address": "1461 Coral Ridge Ave, Coralville, IA 52241",
      "city": "Coralville",
      "state": "IA",
      "zip": "52241",
      "lat": 41.6749,
      "lng": -91.577,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Iowa City Scheels."
    },
    {
      "id": "oak-hill-outdoor-milford-ia",
      "name": "Oak Hill Outdoor",
      "category": "retail",
      "address": "2188 IA-86, Milford, IA 51351",
      "city": "Milford",
      "state": "IA",
      "zip": "51351",
      "lat": 43.3212,
      "lng": -95.1442,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Oak Hill Outdoor."
    },
    {
      "id": "outdoors-more-inc-cresco-ia",
      "name": "Outdoors & More, Inc.",
      "category": "retail",
      "address": "115 3rd Ave W, Cresco, IA 52136",
      "city": "Cresco",
      "state": "IA",
      "zip": "52136",
      "lat": 43.382,
      "lng": -92.1107,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Outdoors & More, Inc.."
    },
    {
      "id": "plum-creek-archery-dyersville-ia",
      "name": "Plum Creek Archery",
      "category": "retail",
      "address": "204 1st Ave E, Dyersville, IA 52040",
      "city": "Dyersville",
      "state": "IA",
      "zip": "52040",
      "lat": 42.482,
      "lng": -91.1328,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Plum Creek Archery."
    },
    {
      "id": "racks-n-tracks-taxidermy-knoxville-ia",
      "name": "Racks-N-Tracks Taxidermy",
      "category": "retail",
      "address": "796 115th Plaza, Knoxville, IA 50138",
      "city": "Knoxville",
      "state": "IA",
      "zip": "50138",
      "lat": 41.3136,
      "lng": -93.1173,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Racks-N-Tracks Taxidermy."
    },
    {
      "id": "southern-hill-scheels-sioux-city-ia",
      "name": "Southern Hill Scheels",
      "category": "retail",
      "address": "4400 Sergeant Rd Suite 54, Sioux City, IA 51106",
      "city": "Sioux City",
      "state": "IA",
      "zip": "51106",
      "lat": 42.499,
      "lng": -96.4041,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Southern Hill Scheels."
    },
    {
      "id": "tri-state-outdoors-dubuque-ia",
      "name": "Tri-State Outdoors",
      "category": "retail",
      "address": "2100 White St, Dubuque, IA 52001",
      "city": "Dubuque",
      "state": "IA",
      "zip": "52001",
      "lat": 42.5103,
      "lng": -90.66,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Tri-State Outdoors."
    },
    {
      "id": "overland-park-scheels-overland-park-ks",
      "name": "Overland Park Scheels",
      "category": "retail",
      "address": "6503 W 135th St Suite 88, Overland Park, KS 66223",
      "city": "Overland Park",
      "state": "KS",
      "zip": "66223",
      "lat": 38.9738,
      "lng": -94.6729,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Overland Park Scheels."
    },
    {
      "id": "overton-s-archery-lawrence-ks",
      "name": "Overton's Archery",
      "category": "retail",
      "address": "1035 N 3rd St #104, Lawrence, KS 66044",
      "city": "Lawrence",
      "state": "KS",
      "zip": "66044",
      "lat": 38.976,
      "lng": -95.2258,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Overton's Archery."
    },
    {
      "id": "p-s-security-great-bend-ks",
      "name": "P & S Security",
      "category": "retail",
      "address": "255 W Barton County Rd, Great Bend, KS 67530",
      "city": "Great Bend",
      "state": "KS",
      "zip": "67530",
      "lat": 38.37,
      "lng": -98.7712,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at P & S Security."
    },
    {
      "id": "paducah-shooter-s-supply-paducah-ky",
      "name": "Paducah Shooter's Supply",
      "category": "retail",
      "address": "3919 Cairo Road, Paducah, KY 42001",
      "city": "Paducah",
      "state": "KY",
      "zip": "42001",
      "lat": 37.0922,
      "lng": -88.6032,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Paducah Shooter's Supply."
    },
    {
      "id": "uncle-lee-s-llc-buds-gun-shop-greenville-ky",
      "name": "Uncle Lee's LLC (Buds Gun Shop)",
      "category": "retail",
      "address": "820 North Main Street Suite 1, Greenville, KY 42345",
      "city": "Greenville",
      "state": "KY",
      "zip": "42345",
      "lat": 37.2103,
      "lng": -87.1703,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Uncle Lee's LLC (Buds Gun Shop)."
    },
    {
      "id": "simmons-sporting-goods-bastrop-la",
      "name": "Simmons' Sporting Goods",
      "category": "retail",
      "address": "918 N Washington, Bastrop, LA 71220",
      "city": "Bastrop",
      "state": "LA",
      "zip": "71220",
      "lat": 32.7514,
      "lng": -91.868,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Simmons' Sporting Goods."
    },
    {
      "id": "bares-sport-shop-st-charles-mi",
      "name": "Bares Sport Shop",
      "category": "retail",
      "address": "104 E Water St, St Charles, MI 48655",
      "city": "St Charles",
      "state": "MI",
      "zip": "48655",
      "lat": 43.2878,
      "lng": -84.1346,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Bares Sport Shop."
    },
    {
      "id": "d-r-sports-center-kalamazoo-mi",
      "name": "D & R Sports Center",
      "category": "retail",
      "address": "8178 West Main St, Kalamazoo, MI 49009",
      "city": "Kalamazoo",
      "state": "MI",
      "zip": "49009",
      "lat": 42.292,
      "lng": -85.5847,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at D & R Sports Center."
    },
    {
      "id": "hales-true-value-dowagiac-mi",
      "name": "Hales True Value",
      "category": "retail",
      "address": "56216 M51 South, Dowagiac, MI 49047",
      "city": "Dowagiac",
      "state": "MI",
      "zip": "49047",
      "lat": 41.9799,
      "lng": -86.1083,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Hales True Value."
    },
    {
      "id": "northwoods-wholesale-outlet-pinconning-mi",
      "name": "Northwoods Wholesale Outlet",
      "category": "retail",
      "address": "229 W 5th St, Pinconning, MI 48650",
      "city": "Pinconning",
      "state": "MI",
      "zip": "48650",
      "lat": 43.8442,
      "lng": -83.9704,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Northwoods Wholesale Outlet."
    },
    {
      "id": "bwana-archery-little-canada-mn",
      "name": "Bwana Archery",
      "category": "retail",
      "address": "3015 Country Dr, Little Canada, MN 55117",
      "city": "Little Canada",
      "state": "MN",
      "zip": "55117",
      "lat": 45.033,
      "lng": -93.0827,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Bwana Archery."
    },
    {
      "id": "eden-prairie-scheels-eden-prairie-mn",
      "name": "Eden Prairie Scheels",
      "category": "retail",
      "address": "8301 Flying Cloud Dr, Eden Prairie, MN 55344",
      "city": "Eden Prairie",
      "state": "MN",
      "zip": "55344",
      "lat": 44.8537,
      "lng": -93.4693,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Eden Prairie Scheels."
    },
    {
      "id": "joe-s-sporting-goods-ski-shop-st-paul-mn",
      "name": "Joe's Sporting Goods Ski Shop",
      "category": "retail",
      "address": "33 East County Rd B, St. Paul, MN 55117",
      "city": "St. Paul",
      "state": "MN",
      "zip": "55117",
      "lat": 44.9554,
      "lng": -93.0958,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Joe's Sporting Goods Ski Shop."
    },
    {
      "id": "prairie-archery-parkers-prairie-mn",
      "name": "Prairie Archery",
      "category": "retail",
      "address": "1025 South Otter Ave, Parkers Prairie, MN 56361",
      "city": "Parkers Prairie",
      "state": "MN",
      "zip": "56361",
      "lat": 46.1604,
      "lng": -95.3205,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Prairie Archery."
    },
    {
      "id": "river-hills-scheels-mankato-mn",
      "name": "River Hills Scheels",
      "category": "retail",
      "address": "1850 Adams St Suite 6, Mankato, MN 56001",
      "city": "Mankato",
      "state": "MN",
      "zip": "56001",
      "lat": 44.1623,
      "lng": -94.001,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at River Hills Scheels."
    },
    {
      "id": "rochester-scheels-rochester-mn",
      "name": "Rochester Scheels",
      "category": "retail",
      "address": "1220 12th St SW, Rochester, MN 55902",
      "city": "Rochester",
      "state": "MN",
      "zip": "55902",
      "lat": 44.0132,
      "lng": -92.4773,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Rochester Scheels."
    },
    {
      "id": "st-cloud-scheels-st-cloud-mn",
      "name": "St Cloud Scheels",
      "category": "retail",
      "address": "30 N Waite Ave Suite 94, St Cloud, MN 56301",
      "city": "St Cloud",
      "state": "MN",
      "zip": "56301",
      "lat": 45.5608,
      "lng": -94.1577,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at St Cloud Scheels."
    },
    {
      "id": "the-footed-shaft-rochester-mn",
      "name": "The Footed Shaft",
      "category": "retail",
      "address": "5510 Broadway Ave N Suite B, Rochester, MN 55906",
      "city": "Rochester",
      "state": "MN",
      "zip": "55906",
      "lat": 44.007,
      "lng": -92.4769,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at The Footed Shaft."
    },
    {
      "id": "hunting-wholesalers-monroe-city-mo",
      "name": "Hunting Wholesalers",
      "category": "retail",
      "address": "1110 US Highway 24 36 E Suite 14, Monroe City, MO 63456",
      "city": "Monroe City",
      "state": "MO",
      "zip": "63456",
      "lat": 39.6618,
      "lng": -91.7321,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Hunting Wholesalers."
    },
    {
      "id": "jct-tackle-archery-shop-forsyth-mo",
      "name": "JCT Tackle & Archery Shop",
      "category": "retail",
      "address": "20333 US-160, Forsyth, MO 65653",
      "city": "Forsyth",
      "state": "MO",
      "zip": "65653",
      "lat": 36.6883,
      "lng": -93.1148,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at JCT Tackle & Archery Shop."
    },
    {
      "id": "ozark-bait-tackle-llc-versailles-mo",
      "name": "Ozark Bait & Tackle LLC",
      "category": "retail",
      "address": "819 W Newton, Versailles, MO 65084",
      "city": "Versailles",
      "state": "MO",
      "zip": "65084",
      "lat": 38.4311,
      "lng": -92.85,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Ozark Bait & Tackle LLC."
    },
    {
      "id": "beede-outdoors-syracuse-ne",
      "name": "Beede Outdoors",
      "category": "retail",
      "address": "2404 R Road, Syracuse, NE 68446",
      "city": "Syracuse",
      "state": "NE",
      "zip": "68446",
      "lat": 40.6545,
      "lng": -96.1837,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Beede Outdoors."
    },
    {
      "id": "full-draw-archery-omaha-ne",
      "name": "Full Draw Archery",
      "category": "retail",
      "address": "3632 S 144th St, Omaha, NE 68144",
      "city": "Omaha",
      "state": "NE",
      "zip": "68144",
      "lat": 41.2605,
      "lng": -95.9375,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": true,
      "description": "Find Burr Paw at Full Draw Archery."
    },
    {
      "id": "lincoln-scheels-lincoln-ne",
      "name": "Lincoln Scheels",
      "category": "retail",
      "address": "3030 Pine Lake Rd, Lincoln, NE 68516",
      "city": "Lincoln",
      "state": "NE",
      "zip": "68516",
      "lat": 40.8283,
      "lng": -96.6866,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": true,
      "description": "Find Burr Paw at Lincoln Scheels."
    },
    {
      "id": "nexgen-outfitters-sidney-ne",
      "name": "Nexgen Outfitters",
      "category": "retail",
      "address": "100 Commerce CT, Sidney, NE 69162",
      "city": "Sidney",
      "state": "NE",
      "zip": "69162",
      "lat": 41.1378,
      "lng": -102.9789,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Nexgen Outfitters."
    },
    {
      "id": "omaha-scheels-omaha-ne",
      "name": "Omaha Scheels",
      "category": "retail",
      "address": "17202 Davenport St, Omaha, NE 68118",
      "city": "Omaha",
      "state": "NE",
      "zip": "68118",
      "lat": 41.2475,
      "lng": -95.9381,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": true,
      "description": "Find Burr Paw at Omaha Scheels."
    },
    {
      "id": "sand-hills-archery-burwell-ne",
      "name": "Sand Hills Archery",
      "category": "retail",
      "address": "1057 G St, Burwell, NE 68823",
      "city": "Burwell",
      "state": "NE",
      "zip": "68823",
      "lat": 41.7871,
      "lng": -99.1273,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Sand Hills Archery."
    },
    {
      "id": "reno-sparks-scheels-sparks-nv",
      "name": "Reno Sparks Scheels",
      "category": "retail",
      "address": "1200 Scheels Dr, Sparks, NV 89434",
      "city": "Sparks",
      "state": "NV",
      "zip": "89434",
      "lat": 39.5314,
      "lng": -119.7603,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Reno Sparks Scheels."
    },
    {
      "id": "a-m-archery-and-sporting-goods-lakewood-nj",
      "name": "A & M Archery and Sporting Goods",
      "category": "retail",
      "address": "201 Second Street, Lakewood, NJ 08701",
      "city": "Lakewood",
      "state": "NJ",
      "zip": "08701",
      "lat": 40.1001,
      "lng": -74.2264,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at A & M Archery and Sporting Goods."
    },
    {
      "id": "tackle-field-outfitters-wanaque-nj",
      "name": "Tackle & Field Outfitters",
      "category": "retail",
      "address": "81 Ringwood Ave, Wanaque, NJ 07465",
      "city": "Wanaque",
      "state": "NJ",
      "zip": "07465",
      "lat": 41.0369,
      "lng": -74.299,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Tackle & Field Outfitters."
    },
    {
      "id": "archery-shoppe-albuquerque-nm",
      "name": "Archery Shoppe",
      "category": "retail",
      "address": "2910 Carlisle Blvd NE, Albuquerque, NM 87110",
      "city": "Albuquerque",
      "state": "NM",
      "zip": "87110",
      "lat": 35.0855,
      "lng": -106.6435,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Archery Shoppe."
    },
    {
      "id": "b-b-archery-middletown-ny",
      "name": "B & B Archery",
      "category": "retail",
      "address": "562 Vernon Road, Middletown, NY 10940",
      "city": "Middletown",
      "state": "NY",
      "zip": "10940",
      "lat": 41.4376,
      "lng": -74.4302,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at B & B Archery."
    },
    {
      "id": "steiner-s-outpost-watertown-ny",
      "name": "Steiner's Outpost",
      "category": "retail",
      "address": "25523 New York 12, Watertown, NY 13601",
      "city": "Watertown",
      "state": "NY",
      "zip": "13601",
      "lat": 43.9787,
      "lng": -75.9057,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Steiner's Outpost."
    },
    {
      "id": "barefoot-archery-charlotte-nc",
      "name": "Barefoot Archery",
      "category": "retail",
      "address": "4410 Old Pineville Rd, Charlotte, NC 28217",
      "city": "Charlotte",
      "state": "NC",
      "zip": "28217",
      "lat": 35.22,
      "lng": -80.8504,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Barefoot Archery."
    },
    {
      "id": "fargo-scheels-fargo-nd",
      "name": "Fargo Scheels",
      "category": "retail",
      "address": "1551 45th St S, Fargo, ND 58103",
      "city": "Fargo",
      "state": "ND",
      "zip": "58103",
      "lat": 46.8797,
      "lng": -96.7805,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Fargo Scheels."
    },
    {
      "id": "big-bucks-archery-shop-st-henry-oh",
      "name": "Big Bucks Archery Shop",
      "category": "retail",
      "address": "2484 US Route 127, St Henry, OH 45883",
      "city": "St Henry",
      "state": "OH",
      "zip": "45883",
      "lat": 40.4222,
      "lng": -84.6429,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Big Bucks Archery Shop."
    },
    {
      "id": "fin-feather-fur-outfitters-ashland-ashland-oh",
      "name": "Fin Feather Fur Outfitters (Ashland)",
      "category": "retail",
      "address": "652 US-250, Ashland, OH 44805",
      "city": "Ashland",
      "state": "OH",
      "zip": "44805",
      "lat": 40.8716,
      "lng": -82.3106,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Fin Feather Fur Outfitters (Ashland)."
    },
    {
      "id": "fin-feather-fur-outfitters-canton-canton-oh",
      "name": "Fin Feather Fur Outfitters (Canton)",
      "category": "retail",
      "address": "4080 Belden Village St NW, Canton, OH 44718",
      "city": "Canton",
      "state": "OH",
      "zip": "44718",
      "lat": 40.807,
      "lng": -81.3844,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Fin Feather Fur Outfitters (Canton)."
    },
    {
      "id": "fin-feather-fur-outfitters-middleburg-heights-middleburg-hei",
      "name": "Fin Feather Fur Outfitters (Middleburg Heights)",
      "category": "retail",
      "address": "18030 Bagley Rd, Middleburg Heights, OH 44130",
      "city": "Middleburg Heights",
      "state": "OH",
      "zip": "44130",
      "lat": 41.3534,
      "lng": -81.8033,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Fin Feather Fur Outfitters (Middleburg Heights)."
    },
    {
      "id": "fin-feather-fur-outfitters-milan-milan-oh",
      "name": "Fin Feather Fur Outfitters (Milan)",
      "category": "retail",
      "address": "12400 US 250 N, Milan, OH 44846",
      "city": "Milan",
      "state": "OH",
      "zip": "44846",
      "lat": 41.2959,
      "lng": -82.6151,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Fin Feather Fur Outfitters (Milan)."
    },
    {
      "id": "fin-feather-fur-outfitters-rossford-rossford-oh",
      "name": "Fin Feather Fur Outfitters (Rossford)",
      "category": "retail",
      "address": "27171 Crossroads Pkwy, Rossford, OH 43460",
      "city": "Rossford",
      "state": "OH",
      "zip": "43460",
      "lat": 41.6016,
      "lng": -83.5541,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Fin Feather Fur Outfitters (Rossford)."
    },
    {
      "id": "fin-feather-fur-outfitters-youngstown-youngstown-oh",
      "name": "Fin Feather Fur Outfitters (Youngstown)",
      "category": "retail",
      "address": "1138 Boardman Poland Rd, Youngstown, OH 44514",
      "city": "Youngstown",
      "state": "OH",
      "zip": "44514",
      "lat": 41.0969,
      "lng": -80.6434,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Fin Feather Fur Outfitters (Youngstown)."
    },
    {
      "id": "mobile-hunting-solutions-millersburg-oh",
      "name": "Mobile Hunting Solutions",
      "category": "retail",
      "address": "6652 County Road 203, Millersburg, OH 44654",
      "city": "Millersburg",
      "state": "OH",
      "zip": "44654",
      "lat": 40.5537,
      "lng": -81.9118,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Mobile Hunting Solutions."
    },
    {
      "id": "peregrine-outdoor-products-lebanon-oh",
      "name": "Peregrine Outdoor Products",
      "category": "retail",
      "address": "4317 N State Route 48, Lebanon, OH 45036",
      "city": "Lebanon",
      "state": "OH",
      "zip": "45036",
      "lat": 39.4431,
      "lng": -84.2129,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Peregrine Outdoor Products."
    },
    {
      "id": "d-r-firearms-belleville-pa",
      "name": "D & R Firearms",
      "category": "retail",
      "address": "2459 PA-655, Belleville, PA 17004",
      "city": "Belleville",
      "state": "PA",
      "zip": "17004",
      "lat": 40.6097,
      "lng": -77.7281,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at D & R Firearms."
    },
    {
      "id": "stone-creek-hunting-and-outdoor-gear-hesston-pa",
      "name": "Stone Creek Hunting and Outdoor Gear",
      "category": "retail",
      "address": "11637 Redstone Ridge Rd, Hesston, PA 16647",
      "city": "Hesston",
      "state": "PA",
      "zip": "16647",
      "lat": 40.439,
      "lng": -78.1344,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Stone Creek Hunting and Outdoor Gear."
    },
    {
      "id": "jeff-s-gun-vault-winner-sd",
      "name": "Jeff's Gun Vault",
      "category": "retail",
      "address": "757 W 2nd St, Winner, SD 57580",
      "city": "Winner",
      "state": "SD",
      "zip": "57580",
      "lat": 43.3681,
      "lng": -99.8555,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Jeff's Gun Vault."
    },
    {
      "id": "sioux-falls-scheels-sioux-falls-sd",
      "name": "Sioux Falls Scheels",
      "category": "retail",
      "address": "2101 W 41st St, Sioux Falls, SD 57105",
      "city": "Sioux Falls",
      "state": "SD",
      "zip": "57105",
      "lat": 43.5389,
      "lng": -96.7235,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Sioux Falls Scheels."
    },
    {
      "id": "taylors-archery-tullahoma-tn",
      "name": "Taylors Archery",
      "category": "retail",
      "address": "100 E Lauderdale St, Tullahoma, TN 37388",
      "city": "Tullahoma",
      "state": "TN",
      "zip": "37388",
      "lat": 35.3712,
      "lng": -86.2114,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Taylors Archery."
    },
    {
      "id": "rack-n-reel-new-haven-vt",
      "name": "Rack N Reel",
      "category": "retail",
      "address": "5343 Ethan Allen HWY, New Haven, VT 05472",
      "city": "New Haven",
      "state": "VT",
      "zip": "05472",
      "lat": 44.1262,
      "lng": -73.2119,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Rack N Reel."
    },
    {
      "id": "r-l-archery-barre-vt",
      "name": "R & L Archery",
      "category": "retail",
      "address": "70 Smith St, Barre, VT 05641",
      "city": "Barre",
      "state": "VT",
      "zip": "05641",
      "lat": 44.2003,
      "lng": -72.4998,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at R & L Archery."
    },
    {
      "id": "pembroke-stop-n-save-pembroke-va",
      "name": "Pembroke Stop N Save",
      "category": "retail",
      "address": "138 Grill Rd, Pembroke, VA 24136",
      "city": "Pembroke",
      "state": "VA",
      "zip": "24136",
      "lat": 37.3259,
      "lng": -80.6442,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Pembroke Stop N Save."
    },
    {
      "id": "a-1-archery-hudson-wi",
      "name": "A-1 Archery",
      "category": "retail",
      "address": "587 Lenertz Rd, Hudson, WI 54016",
      "city": "Hudson",
      "state": "WI",
      "zip": "54016",
      "lat": 44.9804,
      "lng": -92.7547,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at A-1 Archery."
    },
    {
      "id": "appleton-scheels-appleton-wi",
      "name": "Appleton Scheels",
      "category": "retail",
      "address": "4301 W Wisconsin Ave Suite 015, Appleton, WI 54913",
      "city": "Appleton",
      "state": "WI",
      "zip": "54913",
      "lat": 44.2592,
      "lng": -88.4128,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Appleton Scheels."
    },
    {
      "id": "eau-claire-scheels-eau-claire-wi",
      "name": "Eau Claire Scheels",
      "category": "retail",
      "address": "4710 Golf Rd, Eau Claire, WI 54701",
      "city": "Eau Claire",
      "state": "WI",
      "zip": "54701",
      "lat": 44.8126,
      "lng": -91.5015,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Eau Claire Scheels."
    },
    {
      "id": "hunt-n-gear-janesville-wi",
      "name": "Hunt-N-Gear",
      "category": "retail",
      "address": "4336 Milton Ave Suite 140, Janesville, WI 53546",
      "city": "Janesville",
      "state": "WI",
      "zip": "53546",
      "lat": 42.6911,
      "lng": -89.0191,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Hunt-N-Gear."
    },
    {
      "id": "the-smoking-gun-llc-rockland-wi",
      "name": "The Smoking Gun LLC",
      "category": "retail",
      "address": "1455 S Walnut St, Rockland, WI 54653",
      "city": "Rockland",
      "state": "WI",
      "zip": "54653",
      "lat": 43.9163,
      "lng": -90.9272,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at The Smoking Gun LLC."
    },
    {
      "id": "tibbits-archery-mineral-point-wi",
      "name": "Tibbits Archery",
      "category": "retail",
      "address": "760 Lost Grove Rd, Mineral Point, WI 53565",
      "city": "Mineral Point",
      "state": "WI",
      "zip": "53565",
      "lat": 42.8648,
      "lng": -90.1875,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Tibbits Archery."
    },
    {
      "id": "west-town-archery-brookfield-wi",
      "name": "West Town Archery",
      "category": "retail",
      "address": "4135 N 126th St, Brookfield, WI 53005",
      "city": "Brookfield",
      "state": "WI",
      "zip": "53005",
      "lat": 43.0665,
      "lng": -88.1149,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at West Town Archery."
    },
    {
      "id": "wicked-archery-richfield-wi",
      "name": "Wicked Archery",
      "category": "retail",
      "address": "3010 D Helsan Dr, Richfield, WI 53076",
      "city": "Richfield",
      "state": "WI",
      "zip": "53076",
      "lat": 43.2616,
      "lng": -88.1922,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Wicked Archery."
    },
    {
      "id": "summit-archery-hastings-ne",
      "name": "Summit Archery",
      "category": "retail",
      "address": "1207 West J Street, Hastings, NE 68901",
      "city": "Hastings",
      "state": "NE",
      "zip": "68901",
      "lat": 40.5883,
      "lng": -98.3799,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Summit Archery."
    },
    {
      "id": "equip-it-inc-newton-il",
      "name": "Equip-It INC",
      "category": "retail",
      "address": "8787 Commercial Ave, Newton, IL 62448",
      "city": "Newton",
      "state": "IL",
      "zip": "62448",
      "lat": 38.9894,
      "lng": -88.1679,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Equip-It INC."
    },
    {
      "id": "coteau-views-conde-sd",
      "name": "Coteau Views",
      "category": "retail",
      "address": "40746 144th Street, Conde, SD 57434",
      "city": "Conde",
      "state": "SD",
      "zip": "57434",
      "lat": 45.1616,
      "lng": -98.0979,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Coteau Views."
    },
    {
      "id": "joes-sporting-goods-clare-mi",
      "name": "Joes Sporting Goods",
      "category": "retail",
      "address": "8800 South Clare Avenue, Clare, MI 48617",
      "city": "Clare",
      "state": "MI",
      "zip": "48617",
      "lat": 43.8213,
      "lng": -84.7645,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Joes Sporting Goods."
    },
    {
      "id": "dakota-mart-pierre-sd",
      "name": "Dakota Mart",
      "category": "retail",
      "address": "120 West Sioux Avenue, Pierre, SD 57501",
      "city": "Pierre",
      "state": "SD",
      "zip": "57501",
      "lat": 44.3611,
      "lng": -100.342,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Dakota Mart."
    },
    {
      "id": "anchor-inn-bait-tackle-council-bluffs-ia",
      "name": "Anchor Inn Bait & Tackle",
      "category": "retail",
      "address": "1201 Veterans Memorial Hwy, Council Bluffs, IA 51501",
      "city": "Council Bluffs",
      "state": "IA",
      "zip": "51501",
      "lat": 41.2529,
      "lng": -95.8705,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Anchor Inn Bait & Tackle."
    },
    {
      "id": "sport-shed-etc-ord-ne",
      "name": "Sport Shed Etc",
      "category": "retail",
      "address": "317 S 14th St, Ord, NE 68862",
      "city": "Ord",
      "state": "NE",
      "zip": "68862",
      "lat": 41.6114,
      "lng": -98.9222,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Sport Shed Etc."
    },
    {
      "id": "lewis-access-outfitters-center-point-ia",
      "name": "Lewis Access Outfitters",
      "category": "retail",
      "address": "807 Mustang Ln, Center Point, IA 52213",
      "city": "Center Point",
      "state": "IA",
      "zip": "52213",
      "lat": 42.1891,
      "lng": -91.794,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Lewis Access Outfitters."
    },
    {
      "id": "armadillo-arms-and-sporting-goods-mccook-ne",
      "name": "Armadillo Arms and Sporting Goods",
      "category": "retail",
      "address": "210 Airport Road, McCook, NE 69001",
      "city": "McCook",
      "state": "NE",
      "zip": "69001",
      "lat": 40.202,
      "lng": -100.6294,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Armadillo Arms and Sporting Goods."
    },
    {
      "id": "goldstar-outdoors-edmore-mi",
      "name": "Goldstar Outdoors",
      "category": "retail",
      "address": "358 W M-46, Edmore, MI 48829",
      "city": "Edmore",
      "state": "MI",
      "zip": "48829",
      "lat": 43.4133,
      "lng": -85.0352,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Goldstar Outdoors."
    },
    {
      "id": "omaha-outfitters-gretna-ne",
      "name": "Omaha Outfitters",
      "category": "retail",
      "address": "11314 Wickersham Blvd Ste 700, Gretna, NE 68028",
      "city": "Gretna",
      "state": "NE",
      "zip": "68028",
      "lat": 41.1342,
      "lng": -96.2459,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Omaha Outfitters."
    },
    {
      "id": "base-outfitters-range-knob-noster-mo",
      "name": "Base Outfitters & Range",
      "category": "retail",
      "address": "801 Deerbrook Cir, Knob Noster, MO 65336",
      "city": "Knob Noster",
      "state": "MO",
      "zip": "65336",
      "lat": 38.7722,
      "lng": -93.5516,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Base Outfitters & Range."
    },
    {
      "id": "robin-pheasant-cove-outfitters-glenham-sd",
      "name": "Robin Pheasant Cove Outfitters",
      "category": "retail",
      "address": "101 5th Ave, Glenham, SD 57631",
      "city": "Glenham",
      "state": "SD",
      "zip": "57631",
      "lat": 45.5364,
      "lng": -100.2735,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Robin Pheasant Cove Outfitters."
    },
    {
      "id": "route-66-sporting-goods-inc-shippenville-pa",
      "name": "Route 66 Sporting Goods, Inc.",
      "category": "retail",
      "address": "23066 Route 66, Shippenville, PA 16254",
      "city": "Shippenville",
      "state": "PA",
      "zip": "16254",
      "lat": 41.2545,
      "lng": -79.4564,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Route 66 Sporting Goods, Inc.."
    },
    {
      "id": "sommerfeld-outfitters-lidderdale-ia",
      "name": "Sommerfeld Outfitters",
      "category": "retail",
      "address": "330 S Main St, Lidderdale, IA 51452",
      "city": "Lidderdale",
      "state": "IA",
      "zip": "51452",
      "lat": 42.1259,
      "lng": -94.7753,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Sommerfeld Outfitters."
    },
    {
      "id": "iowa-river-outdoors-swisher-ia",
      "name": "Iowa River Outdoors",
      "category": "retail",
      "address": "2721 120th St NE Ste C, Swisher, IA 52338",
      "city": "Swisher",
      "state": "IA",
      "zip": "52338",
      "lat": 41.8389,
      "lng": -91.6433,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Iowa River Outdoors."
    },
    {
      "id": "theisen-s-dubuque-dubuque-ia",
      "name": "Theisen's Dubuque",
      "category": "retail",
      "address": "2900 Dodge St, Dubuque, IA 52003",
      "city": "Dubuque",
      "state": "IA",
      "zip": "52003",
      "lat": 42.5094,
      "lng": -90.6601,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Dubuque."
    },
    {
      "id": "theisen-s-maquoketa-maquoketa-ia",
      "name": "Theisen's Maquoketa",
      "category": "retail",
      "address": "18195 Hwy 64 West, Maquoketa, IA 52060",
      "city": "Maquoketa",
      "state": "IA",
      "zip": "52060",
      "lat": 42.0659,
      "lng": -90.6721,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Maquoketa."
    },
    {
      "id": "theisen-s-dewitt-dewitt-ia",
      "name": "Theisen's Dewitt",
      "category": "retail",
      "address": "316 East 11th St, DeWitt, IA 52742",
      "city": "DeWitt",
      "state": "IA",
      "zip": "52742",
      "lat": 41.8237,
      "lng": -90.5432,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Dewitt."
    },
    {
      "id": "theisen-s-anamosa-anamosa-ia",
      "name": "Theisen's Anamosa",
      "category": "retail",
      "address": "102 Chamber Drive, Anamosa, IA 52205",
      "city": "Anamosa",
      "state": "IA",
      "zip": "52205",
      "lat": 42.1179,
      "lng": -91.2865,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Anamosa."
    },
    {
      "id": "theisen-s-monticello-monticello-ia",
      "name": "Theisen's Monticello",
      "category": "retail",
      "address": "220 S. Main St., Monticello, IA 52310",
      "city": "Monticello",
      "state": "IA",
      "zip": "52310",
      "lat": 42.2415,
      "lng": -91.1864,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Monticello."
    },
    {
      "id": "theisen-s-dyersville-dyersville-ia",
      "name": "Theisen's Dyersville",
      "category": "retail",
      "address": "1222 9th St. SE, Dyersville, IA 52040",
      "city": "Dyersville",
      "state": "IA",
      "zip": "52040",
      "lat": 42.4767,
      "lng": -91.1247,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Dyersville."
    },
    {
      "id": "theisen-s-vinton-vinton-ia",
      "name": "Theisen's Vinton",
      "category": "retail",
      "address": "1405 Hwy 218 South, Vinton, IA 52349",
      "city": "Vinton",
      "state": "IA",
      "zip": "52349",
      "lat": 42.1702,
      "lng": -92.0224,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Vinton."
    },
    {
      "id": "theisen-s-iowa-falls-iowa-falls-ia",
      "name": "Theisen's Iowa Falls",
      "category": "retail",
      "address": "702 Ellsworth Ave., Iowa Falls, IA 50126",
      "city": "Iowa Falls",
      "state": "IA",
      "zip": "50126",
      "lat": 42.5136,
      "lng": -93.2658,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Iowa Falls."
    },
    {
      "id": "theisen-s-charles-city-charles-city-ia",
      "name": "Theisen's Charles City",
      "category": "retail",
      "address": "803 Kelly St., Charles City, IA 50616",
      "city": "Charles City",
      "state": "IA",
      "zip": "50616",
      "lat": 43.0597,
      "lng": -92.6663,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Charles City."
    },
    {
      "id": "theisen-s-new-hampton-new-hampton-ia",
      "name": "Theisen's New Hampton",
      "category": "retail",
      "address": "660 West Milwaukee St, New Hampton, IA 50659",
      "city": "New Hampton",
      "state": "IA",
      "zip": "50659",
      "lat": 43.0511,
      "lng": -92.3129,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's New Hampton."
    },
    {
      "id": "theisen-s-marshalltown-marshalltown-ia",
      "name": "Theisen's Marshalltown",
      "category": "retail",
      "address": "602 Iowa Ave W, Marshalltown, IA 50158",
      "city": "Marshalltown",
      "state": "IA",
      "zip": "50158",
      "lat": 42.0469,
      "lng": -92.9026,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Marshalltown."
    },
    {
      "id": "theisen-s-cedar-rapids-sw-cedar-rapids-ia",
      "name": "Theisen's Cedar Rapids SW",
      "category": "retail",
      "address": "3111 16th Ave. SW, Cedar Rapids, IA 52404",
      "city": "Cedar Rapids",
      "state": "IA",
      "zip": "52404",
      "lat": 41.9805,
      "lng": -91.656,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Cedar Rapids SW."
    },
    {
      "id": "theisen-s-newton-newton-ia",
      "name": "Theisen's Newton",
      "category": "retail",
      "address": "3021 1st Ave. E, Newton, IA 50208",
      "city": "Newton",
      "state": "IA",
      "zip": "50208",
      "lat": 41.6962,
      "lng": -93.0576,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Newton."
    },
    {
      "id": "theisen-s-ames-ames-ia",
      "name": "Theisen's Ames",
      "category": "retail",
      "address": "1315 South Dayton Ave., Ames, IA 50010",
      "city": "Ames",
      "state": "IA",
      "zip": "50010",
      "lat": 42.0209,
      "lng": -93.6331,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Ames."
    },
    {
      "id": "theisen-s-grinnell-grinnell-ia",
      "name": "Theisen's Grinnell",
      "category": "retail",
      "address": "208 West Street S., Grinnell, IA 50112",
      "city": "Grinnell",
      "state": "IA",
      "zip": "50112",
      "lat": 41.7522,
      "lng": -92.7247,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Grinnell."
    },
    {
      "id": "theisen-s-pella-pella-ia",
      "name": "Theisen's Pella",
      "category": "retail",
      "address": "403 East Oskaloosa, Pella, IA 50219",
      "city": "Pella",
      "state": "IA",
      "zip": "50219",
      "lat": 41.3982,
      "lng": -92.922,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Pella."
    },
    {
      "id": "theisen-s-coralville-coralville-ia",
      "name": "Theisen's Coralville",
      "category": "retail",
      "address": "100 Westcor Drive, Coralville, IA 52241",
      "city": "Coralville",
      "state": "IA",
      "zip": "52241",
      "lat": 41.6742,
      "lng": -91.5797,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Coralville."
    },
    {
      "id": "theisen-s-cedar-rapids-ne-cedar-rapids-ia",
      "name": "Theisen's Cedar Rapids NE",
      "category": "retail",
      "address": "1800 51st Street NE, Cedar Rapids, IA 52402",
      "city": "Cedar Rapids",
      "state": "IA",
      "zip": "52402",
      "lat": 41.9814,
      "lng": -91.6749,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Cedar Rapids NE."
    },
    {
      "id": "theisen-s-indianola-indianola-ia",
      "name": "Theisen's Indianola",
      "category": "retail",
      "address": "2312 N. Jefferson Way, Indianola, IA 50125",
      "city": "Indianola",
      "state": "IA",
      "zip": "50125",
      "lat": 41.3547,
      "lng": -93.5564,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Indianola."
    },
    {
      "id": "theisen-s-sparta-sparta-wi",
      "name": "Theisen's Sparta",
      "category": "retail",
      "address": "3000 S. Black River St., Sparta, WI 54656",
      "city": "Sparta",
      "state": "WI",
      "zip": "54656",
      "lat": 43.9492,
      "lng": -90.8071,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Sparta."
    },
    {
      "id": "theisen-s-black-river-falls-black-river-falls-wi",
      "name": "Theisen's Black River Falls",
      "category": "retail",
      "address": "616 State Hwy 54, Black River Falls, WI 54615",
      "city": "Black River Falls",
      "state": "WI",
      "zip": "54615",
      "lat": 44.2899,
      "lng": -90.844,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Black River Falls."
    },
    {
      "id": "theisen-s-davenport-davenport-ia",
      "name": "Theisen's Davenport",
      "category": "retail",
      "address": "3808 Brady St., Davenport, IA 52806",
      "city": "Davenport",
      "state": "IA",
      "zip": "52806",
      "lat": 41.5266,
      "lng": -90.5863,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Davenport."
    },
    {
      "id": "theisen-s-jefferson-jefferson-wi",
      "name": "Theisen's Jefferson",
      "category": "retail",
      "address": "1525 S. Ryan Ave., Jefferson, WI 53549",
      "city": "Jefferson",
      "state": "WI",
      "zip": "53549",
      "lat": 43.005,
      "lng": -88.8029,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Jefferson."
    },
    {
      "id": "theisen-s-ripon-ripon-wi",
      "name": "Theisen's Ripon",
      "category": "retail",
      "address": "1200 W Fond Du Lac St, Ripon, WI 54971",
      "city": "Ripon",
      "state": "WI",
      "zip": "54971",
      "lat": 43.8342,
      "lng": -88.8283,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Ripon."
    },
    {
      "id": "theisen-s-neenah-neenah-wi",
      "name": "Theisen's Neenah",
      "category": "retail",
      "address": "999 Winneconne Ave, Neenah, WI 54956",
      "city": "Neenah",
      "state": "WI",
      "zip": "54956",
      "lat": 44.1826,
      "lng": -88.4592,
      "hours": "Store hours vary",
      "schedule": "Year-round",
      "featured": false,
      "description": "Find Burr Paw at Theisen's Neenah."
    }
  ]
};
