window.BURR_PAW_LOCATIONS = {
  locations: [
    {
      id: "scheels-omaha",
      name: "SCHEELS Omaha",
      category: "retail",
      address: "17202 Davenport St, Omaha, NE 68118",
      city: "Omaha",
      state: "NE",
      zip: "68118",
      lat: 41.2668,
      lng: -96.1824,
      hours: "Store hours vary",
      schedule: "Year-round",
      featured: true,
      description: "Find Burr Paw at SCHEELS Omaha.",
    },
    {
      id: "home-depot-omaha",
      name: "The Home Depot — NW Omaha",
      category: "retail",
      address: "3950 N 144th St, Omaha, NE 68116",
      city: "Omaha",
      state: "NE",
      zip: "68116",
      lat: 41.2947,
      lng: -96.1412,
      hours: "Store hours vary",
      schedule: "Year-round",
      featured: true,
      description: "Find Burr Paw at The Home Depot in NW Omaha.",
    },
  ],
};
